// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"

	"github.com/boreq/eggplant/adapters"
	auth2 "github.com/boreq/eggplant/adapters/auth"
	"github.com/boreq/eggplant/adapters/music/library"
	"github.com/boreq/eggplant/adapters/music/tracks"
	"github.com/boreq/eggplant/adapters/pubsub"
	remote2 "github.com/boreq/eggplant/adapters/remote"
	"github.com/boreq/eggplant/application"
	"github.com/boreq/eggplant/application/auth"
	"github.com/boreq/eggplant/application/music"
	"github.com/boreq/eggplant/application/queries"
	"github.com/boreq/eggplant/application/remote"
	"github.com/boreq/eggplant/entrypoints/filesystem"
	"github.com/boreq/eggplant/entrypoints/http"
	"github.com/boreq/eggplant/entrypoints/outbox"
	"github.com/boreq/eggplant/internal/config"
	"github.com/boreq/eggplant/internal/service"
	"go.etcd.io/bbolt"
)

// Injectors from wire.go:

func BuildTransactableAuthRepositories(tx *bbolt.Tx) (*auth.TransactableRepositories, error) {
	invitationRepository, err := auth2.NewInvitationRepository(tx)
	if err != nil {
		return nil, err
	}
	userRepository, err := auth2.NewUserRepository(tx)
	if err != nil {
		return nil, err
	}
	transactableRepositories := &auth.TransactableRepositories{
		Invitations: invitationRepository,
		Users:       userRepository,
	}
	return transactableRepositories, nil
}

func BuildTransactableQueryRepositories(tx *bbolt.Tx) (*queries.TransactableRepositories, error) {
	userRepository, err := auth2.NewUserRepository(tx)
	if err != nil {
		return nil, err
	}
	transactableRepositories := &queries.TransactableRepositories{
		Users: userRepository,
	}
	return transactableRepositories, nil
}

func BuildAuthForTest(db *bbolt.DB) (*auth.Auth, error) {
	bcryptPasswordHasher := auth2.NewBcryptPasswordHasher()
	wireAuthRepositoriesProvider := newAuthRepositoriesProvider()
	authTransactionProvider := auth2.NewAuthTransactionProvider(db, wireAuthRepositoriesProvider)
	registerInitialHandler := auth.NewRegisterInitialHandler(bcryptPasswordHasher, authTransactionProvider)
	registerHandler := auth.NewRegisterHandler(bcryptPasswordHasher, authTransactionProvider)
	loginHandler := auth.NewLoginHandler(bcryptPasswordHasher, authTransactionProvider)
	logoutHandler := auth.NewLogoutHandler(authTransactionProvider)
	lastSeenUpdater := auth2.NewLastSeenUpdater()
	checkAccessTokenHandler := auth.NewCheckAccessTokenHandler(authTransactionProvider, lastSeenUpdater)
	listHandler := auth.NewListHandler(authTransactionProvider)
	createInvitationHandler := auth.NewCreateInvitationHandler(authTransactionProvider)
	removeHandler := auth.NewRemoveHandler(authTransactionProvider)
	setPasswordHandler := auth.NewSetPasswordHandler(bcryptPasswordHasher, authTransactionProvider)
	getCurrentUserHandler := auth.NewGetCurrentUserHandler(authTransactionProvider)
	authAuth := &auth.Auth{
		RegisterInitial:  registerInitialHandler,
		Register:         registerHandler,
		Login:            loginHandler,
		Logout:           logoutHandler,
		CheckAccessToken: checkAccessTokenHandler,
		List:             listHandler,
		CreateInvitation: createInvitationHandler,
		Remove:           removeHandler,
		SetPassword:      setPasswordHandler,
		GetCurrentUser:   getCurrentUserHandler,
	}
	return authAuth, nil
}

func BuildAuth(conf *config.Config) (*auth.Auth, error) {
	bcryptPasswordHasher := auth2.NewBcryptPasswordHasher()
	db, err := newBolt(conf)
	if err != nil {
		return nil, err
	}
	wireAuthRepositoriesProvider := newAuthRepositoriesProvider()
	authTransactionProvider := auth2.NewAuthTransactionProvider(db, wireAuthRepositoriesProvider)
	registerInitialHandler := auth.NewRegisterInitialHandler(bcryptPasswordHasher, authTransactionProvider)
	registerHandler := auth.NewRegisterHandler(bcryptPasswordHasher, authTransactionProvider)
	loginHandler := auth.NewLoginHandler(bcryptPasswordHasher, authTransactionProvider)
	logoutHandler := auth.NewLogoutHandler(authTransactionProvider)
	lastSeenUpdater := auth2.NewLastSeenUpdater()
	checkAccessTokenHandler := auth.NewCheckAccessTokenHandler(authTransactionProvider, lastSeenUpdater)
	listHandler := auth.NewListHandler(authTransactionProvider)
	createInvitationHandler := auth.NewCreateInvitationHandler(authTransactionProvider)
	removeHandler := auth.NewRemoveHandler(authTransactionProvider)
	setPasswordHandler := auth.NewSetPasswordHandler(bcryptPasswordHasher, authTransactionProvider)
	getCurrentUserHandler := auth.NewGetCurrentUserHandler(authTransactionProvider)
	authAuth := &auth.Auth{
		RegisterInitial:  registerInitialHandler,
		Register:         registerHandler,
		Login:            loginHandler,
		Logout:           logoutHandler,
		CheckAccessToken: checkAccessTokenHandler,
		List:             listHandler,
		CreateInvitation: createInvitationHandler,
		Remove:           removeHandler,
		SetPassword:      setPasswordHandler,
		GetCurrentUser:   getCurrentUserHandler,
	}
	return authAuth, nil
}

func BuildTransactableRemoteRepositories(tx *bbolt.Tx) (*remote.TransactableRepositories, error) {
	remoteInstanceRepository, err := remote2.NewRemoteInstanceRepository(tx)
	if err != nil {
		return nil, err
	}
	outboxRepository, err := adapters.NewOutboxRepository(tx)
	if err != nil {
		return nil, err
	}
	transactableRepositories := &remote.TransactableRepositories{
		RemoteInstances: remoteInstanceRepository,
		Outbox:          outboxRepository,
	}
	return transactableRepositories, nil
}

func BuildService(ctx context.Context, conf *config.Config) (*service.Service, error) {
	bcryptPasswordHasher := auth2.NewBcryptPasswordHasher()
	db, err := newBolt(conf)
	if err != nil {
		return nil, err
	}
	wireAuthRepositoriesProvider := newAuthRepositoriesProvider()
	authTransactionProvider := auth2.NewAuthTransactionProvider(db, wireAuthRepositoriesProvider)
	registerInitialHandler := auth.NewRegisterInitialHandler(bcryptPasswordHasher, authTransactionProvider)
	registerHandler := auth.NewRegisterHandler(bcryptPasswordHasher, authTransactionProvider)
	loginHandler := auth.NewLoginHandler(bcryptPasswordHasher, authTransactionProvider)
	logoutHandler := auth.NewLogoutHandler(authTransactionProvider)
	lastSeenUpdater := auth2.NewLastSeenUpdater()
	checkAccessTokenHandler := auth.NewCheckAccessTokenHandler(authTransactionProvider, lastSeenUpdater)
	listHandler := auth.NewListHandler(authTransactionProvider)
	createInvitationHandler := auth.NewCreateInvitationHandler(authTransactionProvider)
	removeHandler := auth.NewRemoveHandler(authTransactionProvider)
	setPasswordHandler := auth.NewSetPasswordHandler(bcryptPasswordHasher, authTransactionProvider)
	getCurrentUserHandler := auth.NewGetCurrentUserHandler(authTransactionProvider)
	authAuth := auth.Auth{
		RegisterInitial:  registerInitialHandler,
		Register:         registerHandler,
		Login:            loginHandler,
		Logout:           logoutHandler,
		CheckAccessToken: checkAccessTokenHandler,
		List:             listHandler,
		CreateInvitation: createInvitationHandler,
		Remove:           removeHandler,
		SetPassword:      setPasswordHandler,
		GetCurrentUser:   getCurrentUserHandler,
	}
	inMemoryRepository := library.NewInMemoryRepository()
	thumbnailStore, err := newThumbnailStore(ctx, conf)
	if err != nil {
		return nil, err
	}
	thumbnailHandler := music.NewThumbnailHandler(inMemoryRepository, thumbnailStore)
	v := newMusicHandlerLogger()
	loggingThumbnailHandler := music.NewLoggingThumbnailHandler(thumbnailHandler, v)
	converter, err := newTrackStore(ctx, conf)
	if err != nil {
		return nil, err
	}
	startStreamingHandler := music.NewStartStreamingHandler(inMemoryRepository, converter)
	loggingStartStreamingHandler := music.NewLoggingStartStreamingHandler(startStreamingHandler, v)
	streamPlaylistHandler := music.NewStreamPlaylistHandler(inMemoryRepository, converter)
	loggingStreamPlaylistHandler := music.NewLoggingStreamPlaylistHandler(streamPlaylistHandler, v)
	streamInitHandler := music.NewStreamInitHandler(inMemoryRepository, converter)
	loggingStreamInitHandler := music.NewLoggingStreamInitHandler(streamInitHandler, v)
	streamFragmentHandler := music.NewStreamFragmentHandler(inMemoryRepository, converter)
	loggingStreamFragmentHandler := music.NewLoggingStreamFragmentHandler(streamFragmentHandler, v)
	keepAliveStreamHandler := music.NewKeepAliveStreamHandler(inMemoryRepository, converter)
	loggingKeepAliveStreamHandler := music.NewLoggingKeepAliveStreamHandler(keepAliveStreamHandler, v)
	wireRemoteRepositoriesProvider := newRemoteRepositoriesProvider()
	remoteTransactionProvider := remote2.NewRemoteTransactionProvider(db, wireRemoteRepositoriesProvider)
	remoteClient := remote2.NewRemoteClient()
	remoteLibrary := remote2.NewRemoteLibrary(remoteTransactionProvider, remoteClient)
	getRootAlbumHandler := music.NewGetRootAlbumHandler(inMemoryRepository, remoteLibrary)
	loggingGetRootAlbumHandler := music.NewLoggingGetRootAlbumHandler(getRootAlbumHandler, v)
	getAlbumHandler := music.NewGetAlbumHandler(inMemoryRepository)
	loggingGetAlbumHandler := music.NewLoggingGetAlbumHandler(getAlbumHandler, v)
	remoteGetAlbumHandler := music.NewRemoteGetAlbumHandler(remoteLibrary)
	loggingRemoteGetAlbumHandler := music.NewLoggingRemoteGetAlbumHandler(remoteGetAlbumHandler, v)
	remoteGetThumbnailHandler := music.NewRemoteGetThumbnailHandler(remoteLibrary)
	loggingRemoteGetThumbnailHandler := music.NewLoggingRemoteGetThumbnailHandler(remoteGetThumbnailHandler, v)
	remoteGetTrackDurationHandler := music.NewRemoteGetTrackDurationHandler(remoteLibrary)
	loggingRemoteGetTrackDurationHandler := music.NewLoggingRemoteGetTrackDurationHandler(remoteGetTrackDurationHandler, v)
	remoteStartStreamingHandler := music.NewRemoteStartStreamingHandler(remoteLibrary)
	loggingRemoteStartStreamingHandler := music.NewLoggingRemoteStartStreamingHandler(remoteStartStreamingHandler, v)
	remoteStreamPlaylistHandler := music.NewRemoteStreamPlaylistHandler(remoteLibrary)
	loggingRemoteStreamPlaylistHandler := music.NewLoggingRemoteStreamPlaylistHandler(remoteStreamPlaylistHandler, v)
	remoteStreamInitHandler := music.NewRemoteStreamInitHandler(remoteLibrary)
	loggingRemoteStreamInitHandler := music.NewLoggingRemoteStreamInitHandler(remoteStreamInitHandler, v)
	remoteStreamFragmentHandler := music.NewRemoteStreamFragmentHandler(remoteLibrary)
	loggingRemoteStreamFragmentHandler := music.NewLoggingRemoteStreamFragmentHandler(remoteStreamFragmentHandler, v)
	remoteKeepAliveStreamHandler := music.NewRemoteKeepAliveStreamHandler(remoteLibrary)
	loggingRemoteKeepAliveStreamHandler := music.NewLoggingRemoteKeepAliveStreamHandler(remoteKeepAliveStreamHandler, v)
	ffProbe, err := tracks.NewFFProbe()
	if err != nil {
		return nil, err
	}
	durationStore := tracks.NewDurationStore(ctx, ffProbe)
	getTrackDurationHandler := music.NewGetTrackDurationHandler(inMemoryRepository, durationStore)
	loggingGetTrackDurationHandler := music.NewLoggingGetTrackDurationHandler(getTrackDurationHandler, v)
	searchHandler := music.NewSearchHandler(inMemoryRepository, remoteLibrary)
	loggingSearchHandler := music.NewLoggingSearchHandler(searchHandler, v)
	scannerConfig, err := newScannerConfig(conf)
	if err != nil {
		return nil, err
	}
	scanner, err := newScanner(conf, scannerConfig)
	if err != nil {
		return nil, err
	}
	delimiterAccessLoader := library.NewDelimiterAccessLoader()
	loadLibraryHandler := music.NewLoadLibraryHandler(inMemoryRepository, scanner, converter, thumbnailStore, delimiterAccessLoader, durationStore)
	loggingLoadLibraryHandler := music.NewLoggingLoadLibraryHandler(loadLibraryHandler, v)
	musicMusic := music.Music{
		Thumbnail:              loggingThumbnailHandler,
		StartStreaming:         loggingStartStreamingHandler,
		StreamPlaylist:         loggingStreamPlaylistHandler,
		StreamInit:             loggingStreamInitHandler,
		StreamFragment:         loggingStreamFragmentHandler,
		KeepAliveStream:        loggingKeepAliveStreamHandler,
		GetRootAlbum:           loggingGetRootAlbumHandler,
		GetAlbum:               loggingGetAlbumHandler,
		RemoteGetAlbum:         loggingRemoteGetAlbumHandler,
		RemoteGetThumbnail:     loggingRemoteGetThumbnailHandler,
		RemoteGetTrackDuration: loggingRemoteGetTrackDurationHandler,
		RemoteStartStreaming:   loggingRemoteStartStreamingHandler,
		RemoteStreamPlaylist:   loggingRemoteStreamPlaylistHandler,
		RemoteStreamInit:       loggingRemoteStreamInitHandler,
		RemoteStreamFragment:   loggingRemoteStreamFragmentHandler,
		RemoteKeepAliveStream:  loggingRemoteKeepAliveStreamHandler,
		GetTrackDuration:       loggingGetTrackDurationHandler,
		Search:                 loggingSearchHandler,
		LoadLibrary:            loggingLoadLibraryHandler,
	}
	wireQueryRepositoriesProvider := newQueryRepositoriesProvider()
	queryTransactionProvider := auth2.NewQueryTransactionProvider(db, wireQueryRepositoriesProvider)
	statsHandler := queries.NewStatsHandler(converter, thumbnailStore, queryTransactionProvider)
	applicationQueries := application.Queries{
		Stats: statsHandler,
	}
	addRemoteHandler := remote.NewAddRemoteHandler(remoteTransactionProvider)
	setRemotePairingTokenHandler := remote.NewSetRemotePairingTokenHandler(remoteTransactionProvider)
	sendLocalAuthTokenHandler := remote.NewSendLocalAuthTokenHandler(remoteTransactionProvider, remoteClient)
	setRemoteAuthTokenHandler := remote.NewSetRemoteAuthTokenHandler(remoteTransactionProvider)
	checkLocalAuthTokenHandler := remote.NewCheckLocalAuthTokenHandler(remoteTransactionProvider)
	listRemotesHandler := remote.NewListRemotesHandler(remoteTransactionProvider)
	checkRemotesHandler := remote.NewCheckRemotesHandler(remoteTransactionProvider, remoteClient)
	checkRemoteHandler := remote.NewCheckRemoteHandler(remoteTransactionProvider, remoteClient)
	remoteRemote := remote.Remote{
		AddRemote:             addRemoteHandler,
		SetRemotePairingToken: setRemotePairingTokenHandler,
		SendLocalAuthToken:    sendLocalAuthTokenHandler,
		SetRemoteAuthToken:    setRemoteAuthTokenHandler,
		CheckLocalAuthToken:   checkLocalAuthTokenHandler,
		ListRemotes:           listRemotesHandler,
		CheckRemotes:          checkRemotesHandler,
		CheckRemote:           checkRemoteHandler,
	}
	applicationApplication := &application.Application{
		Auth:    authAuth,
		Music:   musicMusic,
		Queries: applicationQueries,
		Remote:  remoteRemote,
	}
	accessContextProvider := http.NewAccessContextProvider(applicationApplication)
	handler, err := http.NewHandler(applicationApplication, accessContextProvider)
	if err != nil {
		return nil, err
	}
	server := http.NewServer(handler)
	v2, err := newDirectoryWatcherUpdates(conf)
	if err != nil {
		return nil, err
	}
	listener := filesystem.NewListener(loggingLoadLibraryHandler, v2)
	persistLastSeenHandler := auth.NewPersistLastSeenHandler(authTransactionProvider, lastSeenUpdater)
	pubSub, err := pubsub.NewPubSub(db)
	if err != nil {
		return nil, err
	}
	outboxListener := outbox.NewListener(pubSub, sendLocalAuthTokenHandler, checkRemoteHandler)
	serviceService := service.NewService(server, listener, persistLastSeenHandler, checkRemotesHandler, outboxListener, conf)
	return serviceService, nil
}

func BuildTestHTTPService(ctx context.Context, conf *config.Config) (*TestHTTPService, error) {
	bcryptPasswordHasher := auth2.NewBcryptPasswordHasher()
	db, err := newBolt(conf)
	if err != nil {
		return nil, err
	}
	wireAuthRepositoriesProvider := newAuthRepositoriesProvider()
	authTransactionProvider := auth2.NewAuthTransactionProvider(db, wireAuthRepositoriesProvider)
	registerInitialHandler := auth.NewRegisterInitialHandler(bcryptPasswordHasher, authTransactionProvider)
	registerHandler := auth.NewRegisterHandler(bcryptPasswordHasher, authTransactionProvider)
	loginHandler := auth.NewLoginHandler(bcryptPasswordHasher, authTransactionProvider)
	logoutHandler := auth.NewLogoutHandler(authTransactionProvider)
	lastSeenUpdater := auth2.NewLastSeenUpdater()
	checkAccessTokenHandler := auth.NewCheckAccessTokenHandler(authTransactionProvider, lastSeenUpdater)
	listHandler := auth.NewListHandler(authTransactionProvider)
	createInvitationHandler := auth.NewCreateInvitationHandler(authTransactionProvider)
	removeHandler := auth.NewRemoveHandler(authTransactionProvider)
	setPasswordHandler := auth.NewSetPasswordHandler(bcryptPasswordHasher, authTransactionProvider)
	getCurrentUserHandler := auth.NewGetCurrentUserHandler(authTransactionProvider)
	authAuth := auth.Auth{
		RegisterInitial:  registerInitialHandler,
		Register:         registerHandler,
		Login:            loginHandler,
		Logout:           logoutHandler,
		CheckAccessToken: checkAccessTokenHandler,
		List:             listHandler,
		CreateInvitation: createInvitationHandler,
		Remove:           removeHandler,
		SetPassword:      setPasswordHandler,
		GetCurrentUser:   getCurrentUserHandler,
	}
	inMemoryRepository := library.NewInMemoryRepository()
	thumbnailStore, err := newThumbnailStore(ctx, conf)
	if err != nil {
		return nil, err
	}
	thumbnailHandler := music.NewThumbnailHandler(inMemoryRepository, thumbnailStore)
	v := newMusicHandlerLogger()
	loggingThumbnailHandler := music.NewLoggingThumbnailHandler(thumbnailHandler, v)
	converter, err := newTrackStore(ctx, conf)
	if err != nil {
		return nil, err
	}
	startStreamingHandler := music.NewStartStreamingHandler(inMemoryRepository, converter)
	loggingStartStreamingHandler := music.NewLoggingStartStreamingHandler(startStreamingHandler, v)
	streamPlaylistHandler := music.NewStreamPlaylistHandler(inMemoryRepository, converter)
	loggingStreamPlaylistHandler := music.NewLoggingStreamPlaylistHandler(streamPlaylistHandler, v)
	streamInitHandler := music.NewStreamInitHandler(inMemoryRepository, converter)
	loggingStreamInitHandler := music.NewLoggingStreamInitHandler(streamInitHandler, v)
	streamFragmentHandler := music.NewStreamFragmentHandler(inMemoryRepository, converter)
	loggingStreamFragmentHandler := music.NewLoggingStreamFragmentHandler(streamFragmentHandler, v)
	keepAliveStreamHandler := music.NewKeepAliveStreamHandler(inMemoryRepository, converter)
	loggingKeepAliveStreamHandler := music.NewLoggingKeepAliveStreamHandler(keepAliveStreamHandler, v)
	wireRemoteRepositoriesProvider := newRemoteRepositoriesProvider()
	remoteTransactionProvider := remote2.NewRemoteTransactionProvider(db, wireRemoteRepositoriesProvider)
	remoteClient := remote2.NewRemoteClient()
	remoteLibrary := remote2.NewRemoteLibrary(remoteTransactionProvider, remoteClient)
	getRootAlbumHandler := music.NewGetRootAlbumHandler(inMemoryRepository, remoteLibrary)
	loggingGetRootAlbumHandler := music.NewLoggingGetRootAlbumHandler(getRootAlbumHandler, v)
	getAlbumHandler := music.NewGetAlbumHandler(inMemoryRepository)
	loggingGetAlbumHandler := music.NewLoggingGetAlbumHandler(getAlbumHandler, v)
	remoteGetAlbumHandler := music.NewRemoteGetAlbumHandler(remoteLibrary)
	loggingRemoteGetAlbumHandler := music.NewLoggingRemoteGetAlbumHandler(remoteGetAlbumHandler, v)
	remoteGetThumbnailHandler := music.NewRemoteGetThumbnailHandler(remoteLibrary)
	loggingRemoteGetThumbnailHandler := music.NewLoggingRemoteGetThumbnailHandler(remoteGetThumbnailHandler, v)
	remoteGetTrackDurationHandler := music.NewRemoteGetTrackDurationHandler(remoteLibrary)
	loggingRemoteGetTrackDurationHandler := music.NewLoggingRemoteGetTrackDurationHandler(remoteGetTrackDurationHandler, v)
	remoteStartStreamingHandler := music.NewRemoteStartStreamingHandler(remoteLibrary)
	loggingRemoteStartStreamingHandler := music.NewLoggingRemoteStartStreamingHandler(remoteStartStreamingHandler, v)
	remoteStreamPlaylistHandler := music.NewRemoteStreamPlaylistHandler(remoteLibrary)
	loggingRemoteStreamPlaylistHandler := music.NewLoggingRemoteStreamPlaylistHandler(remoteStreamPlaylistHandler, v)
	remoteStreamInitHandler := music.NewRemoteStreamInitHandler(remoteLibrary)
	loggingRemoteStreamInitHandler := music.NewLoggingRemoteStreamInitHandler(remoteStreamInitHandler, v)
	remoteStreamFragmentHandler := music.NewRemoteStreamFragmentHandler(remoteLibrary)
	loggingRemoteStreamFragmentHandler := music.NewLoggingRemoteStreamFragmentHandler(remoteStreamFragmentHandler, v)
	remoteKeepAliveStreamHandler := music.NewRemoteKeepAliveStreamHandler(remoteLibrary)
	loggingRemoteKeepAliveStreamHandler := music.NewLoggingRemoteKeepAliveStreamHandler(remoteKeepAliveStreamHandler, v)
	ffProbe, err := tracks.NewFFProbe()
	if err != nil {
		return nil, err
	}
	durationStore := tracks.NewDurationStore(ctx, ffProbe)
	getTrackDurationHandler := music.NewGetTrackDurationHandler(inMemoryRepository, durationStore)
	loggingGetTrackDurationHandler := music.NewLoggingGetTrackDurationHandler(getTrackDurationHandler, v)
	searchHandler := music.NewSearchHandler(inMemoryRepository, remoteLibrary)
	loggingSearchHandler := music.NewLoggingSearchHandler(searchHandler, v)
	scannerConfig, err := newScannerConfig(conf)
	if err != nil {
		return nil, err
	}
	scanner, err := newScanner(conf, scannerConfig)
	if err != nil {
		return nil, err
	}
	delimiterAccessLoader := library.NewDelimiterAccessLoader()
	loadLibraryHandler := music.NewLoadLibraryHandler(inMemoryRepository, scanner, converter, thumbnailStore, delimiterAccessLoader, durationStore)
	loggingLoadLibraryHandler := music.NewLoggingLoadLibraryHandler(loadLibraryHandler, v)
	musicMusic := music.Music{
		Thumbnail:              loggingThumbnailHandler,
		StartStreaming:         loggingStartStreamingHandler,
		StreamPlaylist:         loggingStreamPlaylistHandler,
		StreamInit:             loggingStreamInitHandler,
		StreamFragment:         loggingStreamFragmentHandler,
		KeepAliveStream:        loggingKeepAliveStreamHandler,
		GetRootAlbum:           loggingGetRootAlbumHandler,
		GetAlbum:               loggingGetAlbumHandler,
		RemoteGetAlbum:         loggingRemoteGetAlbumHandler,
		RemoteGetThumbnail:     loggingRemoteGetThumbnailHandler,
		RemoteGetTrackDuration: loggingRemoteGetTrackDurationHandler,
		RemoteStartStreaming:   loggingRemoteStartStreamingHandler,
		RemoteStreamPlaylist:   loggingRemoteStreamPlaylistHandler,
		RemoteStreamInit:       loggingRemoteStreamInitHandler,
		RemoteStreamFragment:   loggingRemoteStreamFragmentHandler,
		RemoteKeepAliveStream:  loggingRemoteKeepAliveStreamHandler,
		GetTrackDuration:       loggingGetTrackDurationHandler,
		Search:                 loggingSearchHandler,
		LoadLibrary:            loggingLoadLibraryHandler,
	}
	wireQueryRepositoriesProvider := newQueryRepositoriesProvider()
	queryTransactionProvider := auth2.NewQueryTransactionProvider(db, wireQueryRepositoriesProvider)
	statsHandler := queries.NewStatsHandler(converter, thumbnailStore, queryTransactionProvider)
	applicationQueries := application.Queries{
		Stats: statsHandler,
	}
	addRemoteHandler := remote.NewAddRemoteHandler(remoteTransactionProvider)
	setRemotePairingTokenHandler := remote.NewSetRemotePairingTokenHandler(remoteTransactionProvider)
	sendLocalAuthTokenHandler := remote.NewSendLocalAuthTokenHandler(remoteTransactionProvider, remoteClient)
	setRemoteAuthTokenHandler := remote.NewSetRemoteAuthTokenHandler(remoteTransactionProvider)
	checkLocalAuthTokenHandler := remote.NewCheckLocalAuthTokenHandler(remoteTransactionProvider)
	listRemotesHandler := remote.NewListRemotesHandler(remoteTransactionProvider)
	checkRemotesHandler := remote.NewCheckRemotesHandler(remoteTransactionProvider, remoteClient)
	checkRemoteHandler := remote.NewCheckRemoteHandler(remoteTransactionProvider, remoteClient)
	remoteRemote := remote.Remote{
		AddRemote:             addRemoteHandler,
		SetRemotePairingToken: setRemotePairingTokenHandler,
		SendLocalAuthToken:    sendLocalAuthTokenHandler,
		SetRemoteAuthToken:    setRemoteAuthTokenHandler,
		CheckLocalAuthToken:   checkLocalAuthTokenHandler,
		ListRemotes:           listRemotesHandler,
		CheckRemotes:          checkRemotesHandler,
		CheckRemote:           checkRemoteHandler,
	}
	applicationApplication := &application.Application{
		Auth:    authAuth,
		Music:   musicMusic,
		Queries: applicationQueries,
		Remote:  remoteRemote,
	}
	accessContextProvider := http.NewAccessContextProvider(applicationApplication)
	handler, err := http.NewHandler(applicationApplication, accessContextProvider)
	if err != nil {
		return nil, err
	}
	pubSub, err := pubsub.NewPubSub(db)
	if err != nil {
		return nil, err
	}
	listener := outbox.NewListener(pubSub, sendLocalAuthTokenHandler, checkRemoteHandler)
	testHTTPService := newTestHTTPService(handler, applicationApplication, listener, db)
	return testHTTPService, nil
}
