// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"

	auth2 "github.com/boreq/eggplant/adapters/auth"
	"github.com/boreq/eggplant/adapters/music/library"
	"github.com/boreq/eggplant/adapters/music/tracks"
	"github.com/boreq/eggplant/application"
	"github.com/boreq/eggplant/application/auth"
	"github.com/boreq/eggplant/application/music"
	"github.com/boreq/eggplant/application/queries"
	"github.com/boreq/eggplant/entrypoints/filesystem"
	"github.com/boreq/eggplant/entrypoints/http"
	"github.com/boreq/eggplant/internal/config"
	"github.com/boreq/eggplant/internal/service"
	"go.etcd.io/bbolt"
)

// Injectors from wire.go:

func BuildTransactableAuthRepositories(tx *bbolt.Tx) (*auth.TransactableRepositories, error) {
	invitationRepository, err := auth2.NewInvitationRepository(tx)
	if err != nil {
		return nil, err
	}
	userRepository, err := auth2.NewUserRepository(tx)
	if err != nil {
		return nil, err
	}
	transactableRepositories := &auth.TransactableRepositories{
		Invitations: invitationRepository,
		Users:       userRepository,
	}
	return transactableRepositories, nil
}

func BuildTransactableQueryRepositories(tx *bbolt.Tx) (*queries.TransactableRepositories, error) {
	userRepository, err := auth2.NewUserRepository(tx)
	if err != nil {
		return nil, err
	}
	transactableRepositories := &queries.TransactableRepositories{
		Users: userRepository,
	}
	return transactableRepositories, nil
}

func BuildAuthForTest(db *bbolt.DB) (*auth.Auth, error) {
	bcryptPasswordHasher := auth2.NewBcryptPasswordHasher()
	wireAuthRepositoriesProvider := newAuthRepositoriesProvider()
	authTransactionProvider := auth2.NewAuthTransactionProvider(db, wireAuthRepositoriesProvider)
	registerInitialHandler := auth.NewRegisterInitialHandler(bcryptPasswordHasher, authTransactionProvider)
	registerHandler := auth.NewRegisterHandler(bcryptPasswordHasher, authTransactionProvider)
	loginHandler := auth.NewLoginHandler(bcryptPasswordHasher, authTransactionProvider)
	logoutHandler := auth.NewLogoutHandler(authTransactionProvider)
	lastSeenUpdater, err := auth2.NewLastSeenUpdater(authTransactionProvider)
	if err != nil {
		return nil, err
	}
	checkAccessTokenHandler := auth.NewCheckAccessTokenHandler(authTransactionProvider, lastSeenUpdater)
	listHandler := auth.NewListHandler(authTransactionProvider)
	createInvitationHandler := auth.NewCreateInvitationHandler(authTransactionProvider)
	removeHandler := auth.NewRemoveHandler(authTransactionProvider)
	setPasswordHandler := auth.NewSetPasswordHandler(bcryptPasswordHasher, authTransactionProvider)
	authAuth := &auth.Auth{
		RegisterInitial:  registerInitialHandler,
		Register:         registerHandler,
		Login:            loginHandler,
		Logout:           logoutHandler,
		CheckAccessToken: checkAccessTokenHandler,
		List:             listHandler,
		CreateInvitation: createInvitationHandler,
		Remove:           removeHandler,
		SetPassword:      setPasswordHandler,
	}
	return authAuth, nil
}

func BuildAuth(conf *config.Config) (*auth.Auth, error) {
	bcryptPasswordHasher := auth2.NewBcryptPasswordHasher()
	db, err := newBolt(conf)
	if err != nil {
		return nil, err
	}
	wireAuthRepositoriesProvider := newAuthRepositoriesProvider()
	authTransactionProvider := auth2.NewAuthTransactionProvider(db, wireAuthRepositoriesProvider)
	registerInitialHandler := auth.NewRegisterInitialHandler(bcryptPasswordHasher, authTransactionProvider)
	registerHandler := auth.NewRegisterHandler(bcryptPasswordHasher, authTransactionProvider)
	loginHandler := auth.NewLoginHandler(bcryptPasswordHasher, authTransactionProvider)
	logoutHandler := auth.NewLogoutHandler(authTransactionProvider)
	lastSeenUpdater, err := auth2.NewLastSeenUpdater(authTransactionProvider)
	if err != nil {
		return nil, err
	}
	checkAccessTokenHandler := auth.NewCheckAccessTokenHandler(authTransactionProvider, lastSeenUpdater)
	listHandler := auth.NewListHandler(authTransactionProvider)
	createInvitationHandler := auth.NewCreateInvitationHandler(authTransactionProvider)
	removeHandler := auth.NewRemoveHandler(authTransactionProvider)
	setPasswordHandler := auth.NewSetPasswordHandler(bcryptPasswordHasher, authTransactionProvider)
	authAuth := &auth.Auth{
		RegisterInitial:  registerInitialHandler,
		Register:         registerHandler,
		Login:            loginHandler,
		Logout:           logoutHandler,
		CheckAccessToken: checkAccessTokenHandler,
		List:             listHandler,
		CreateInvitation: createInvitationHandler,
		Remove:           removeHandler,
		SetPassword:      setPasswordHandler,
	}
	return authAuth, nil
}

func BuildService(ctx context.Context, conf *config.Config) (*service.Service, error) {
	bcryptPasswordHasher := auth2.NewBcryptPasswordHasher()
	db, err := newBolt(conf)
	if err != nil {
		return nil, err
	}
	wireAuthRepositoriesProvider := newAuthRepositoriesProvider()
	authTransactionProvider := auth2.NewAuthTransactionProvider(db, wireAuthRepositoriesProvider)
	registerInitialHandler := auth.NewRegisterInitialHandler(bcryptPasswordHasher, authTransactionProvider)
	registerHandler := auth.NewRegisterHandler(bcryptPasswordHasher, authTransactionProvider)
	loginHandler := auth.NewLoginHandler(bcryptPasswordHasher, authTransactionProvider)
	logoutHandler := auth.NewLogoutHandler(authTransactionProvider)
	lastSeenUpdater, err := auth2.NewLastSeenUpdater(authTransactionProvider)
	if err != nil {
		return nil, err
	}
	checkAccessTokenHandler := auth.NewCheckAccessTokenHandler(authTransactionProvider, lastSeenUpdater)
	listHandler := auth.NewListHandler(authTransactionProvider)
	createInvitationHandler := auth.NewCreateInvitationHandler(authTransactionProvider)
	removeHandler := auth.NewRemoveHandler(authTransactionProvider)
	setPasswordHandler := auth.NewSetPasswordHandler(bcryptPasswordHasher, authTransactionProvider)
	authAuth := auth.Auth{
		RegisterInitial:  registerInitialHandler,
		Register:         registerHandler,
		Login:            loginHandler,
		Logout:           logoutHandler,
		CheckAccessToken: checkAccessTokenHandler,
		List:             listHandler,
		CreateInvitation: createInvitationHandler,
		Remove:           removeHandler,
		SetPassword:      setPasswordHandler,
	}
	inMemoryRepository := library.NewInMemoryRepository()
	thumbnailStore, err := newThumbnailStore(ctx, conf)
	if err != nil {
		return nil, err
	}
	thumbnailHandler := music.NewThumbnailHandler(inMemoryRepository, thumbnailStore)
	v := newMusicHandlerLogger()
	loggingThumbnailHandler := music.NewLoggingThumbnailHandler(thumbnailHandler, v)
	converter, err := newTrackStore(ctx, conf)
	if err != nil {
		return nil, err
	}
	startStreamingHandler := music.NewStartStreamingHandler(inMemoryRepository, converter)
	loggingStartStreamingHandler := music.NewLoggingStartStreamingHandler(startStreamingHandler, v)
	streamPlaylistHandler := music.NewStreamPlaylistHandler(inMemoryRepository, converter)
	loggingStreamPlaylistHandler := music.NewLoggingStreamPlaylistHandler(streamPlaylistHandler, v)
	streamInitHandler := music.NewStreamInitHandler(inMemoryRepository, converter)
	loggingStreamInitHandler := music.NewLoggingStreamInitHandler(streamInitHandler, v)
	streamFragmentHandler := music.NewStreamFragmentHandler(inMemoryRepository, converter)
	loggingStreamFragmentHandler := music.NewLoggingStreamFragmentHandler(streamFragmentHandler, v)
	keepAliveStreamHandler := music.NewKeepAliveStreamHandler(inMemoryRepository, converter)
	loggingKeepAliveStreamHandler := music.NewLoggingKeepAliveStreamHandler(keepAliveStreamHandler, v)
	getRootAlbumHandler := music.NewGetRootAlbumHandler(inMemoryRepository)
	loggingGetRootAlbumHandler := music.NewLoggingGetRootAlbumHandler(getRootAlbumHandler, v)
	getAlbumHandler := music.NewGetAlbumHandler(inMemoryRepository)
	loggingGetAlbumHandler := music.NewLoggingGetAlbumHandler(getAlbumHandler, v)
	searchHandler := music.NewSearchHandler(inMemoryRepository)
	loggingSearchHandler := music.NewLoggingSearchHandler(searchHandler, v)
	scannerConfig, err := newScannerConfig(conf)
	if err != nil {
		return nil, err
	}
	scanner, err := newScanner(conf, scannerConfig)
	if err != nil {
		return nil, err
	}
	delimiterAccessLoader := library.NewDelimiterAccessLoader()
	ffProbe := tracks.NewFFProbe()
	loadLibraryHandler := music.NewLoadLibraryHandler(inMemoryRepository, scanner, converter, thumbnailStore, delimiterAccessLoader, ffProbe)
	loggingLoadLibraryHandler := music.NewLoggingLoadLibraryHandler(loadLibraryHandler, v)
	applicationMusic := application.Music{
		Thumbnail:       loggingThumbnailHandler,
		StartStreaming:  loggingStartStreamingHandler,
		StreamPlaylist:  loggingStreamPlaylistHandler,
		StreamInit:      loggingStreamInitHandler,
		StreamFragment:  loggingStreamFragmentHandler,
		KeepAliveStream: loggingKeepAliveStreamHandler,
		GetRootAlbum:    loggingGetRootAlbumHandler,
		GetAlbum:        loggingGetAlbumHandler,
		Search:          loggingSearchHandler,
		LoadLibrary:     loggingLoadLibraryHandler,
	}
	wireQueryRepositoriesProvider := newQueryRepositoriesProvider()
	queryTransactionProvider := auth2.NewQueryTransactionProvider(db, wireQueryRepositoriesProvider)
	statsHandler := queries.NewStatsHandler(converter, thumbnailStore, queryTransactionProvider)
	applicationQueries := application.Queries{
		Stats: statsHandler,
	}
	applicationApplication := &application.Application{
		Auth:    authAuth,
		Music:   applicationMusic,
		Queries: applicationQueries,
	}
	accessContextProvider := http.NewAccessContextProvider(applicationApplication)
	handler, err := http.NewHandler(applicationApplication, accessContextProvider)
	if err != nil {
		return nil, err
	}
	server := http.NewServer(handler)
	v2, err := newDirectoryWatcherUpdates(conf)
	if err != nil {
		return nil, err
	}
	listener := filesystem.NewListener(loadLibraryHandler, v2)
	serviceService := service.NewService(server, listener, lastSeenUpdater, conf)
	return serviceService, nil
}
