// Code generated by genhandlers. DO NOT EDIT.

package music

import (
	"context"
	"io"
	"time"

	"github.com/boreq/eggplant/application/accessctx"
	"github.com/boreq/eggplant/domain/music"
	"github.com/boreq/eggplant/domain/music/library"
	"github.com/boreq/eggplant/internal/logging"
)

type LoggingGetAlbumHandler struct {
	inner  *GetAlbumHandler
	logger logging.Logger
}

func NewLoggingGetAlbumHandler(inner *GetAlbumHandler, logger logging.Logger) *LoggingGetAlbumHandler {
	return &LoggingGetAlbumHandler{inner: inner, logger: logger}
}

func (h *LoggingGetAlbumHandler) Execute(accessCtx library.AccessContext, cmd GetAlbum) (music.Album, error) {
	start := time.Now()
	ret0, ret1 := h.inner.Execute(accessCtx, cmd)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret1 != nil && !isNonLoggableError(ret1) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "GetAlbum",
		"accessCtx", accessCtx,
		"cmd", cmd,
		"ret0", ret0,
		"err", ret1,
		"duration", time.Since(start),
	)
	return ret0, ret1
}

type LoggingGetRootAlbumHandler struct {
	inner  *GetRootAlbumHandler
	logger logging.Logger
}

func NewLoggingGetRootAlbumHandler(inner *GetRootAlbumHandler, logger logging.Logger) *LoggingGetRootAlbumHandler {
	return &LoggingGetRootAlbumHandler{inner: inner, logger: logger}
}

func (h *LoggingGetRootAlbumHandler) Execute(ctx context.Context, accessCtx accessctx.AccessContext, cmd GetRootAlbum) (music.RootAlbum, error) {
	start := time.Now()
	ret0, ret1 := h.inner.Execute(ctx, accessCtx, cmd)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret1 != nil && !isNonLoggableError(ret1) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "GetRootAlbum",
		"accessCtx", accessCtx,
		"cmd", cmd,
		"ret0", ret0,
		"err", ret1,
		"duration", time.Since(start),
	)
	return ret0, ret1
}

type LoggingGetTrackDurationHandler struct {
	inner  *GetTrackDurationHandler
	logger logging.Logger
}

func NewLoggingGetTrackDurationHandler(inner *GetTrackDurationHandler, logger logging.Logger) *LoggingGetTrackDurationHandler {
	return &LoggingGetTrackDurationHandler{inner: inner, logger: logger}
}

func (h *LoggingGetTrackDurationHandler) Execute(ctx context.Context, accessCtx library.AccessContext, cmd GetTrackDuration) (music.TrackDuration, error) {
	start := time.Now()
	ret0, ret1 := h.inner.Execute(ctx, accessCtx, cmd)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret1 != nil && !isNonLoggableError(ret1) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "GetTrackDuration",
		"accessCtx", accessCtx,
		"cmd", cmd,
		"ret0", ret0,
		"err", ret1,
		"duration", time.Since(start),
	)
	return ret0, ret1
}

type LoggingKeepAliveStreamHandler struct {
	inner  *KeepAliveStreamHandler
	logger logging.Logger
}

func NewLoggingKeepAliveStreamHandler(inner *KeepAliveStreamHandler, logger logging.Logger) *LoggingKeepAliveStreamHandler {
	return &LoggingKeepAliveStreamHandler{inner: inner, logger: logger}
}

func (h *LoggingKeepAliveStreamHandler) Execute(accessCtx library.AccessContext, cmd KeepAliveStream) error {
	start := time.Now()
	ret0 := h.inner.Execute(accessCtx, cmd)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret0 != nil && !isNonLoggableError(ret0) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "KeepAliveStream",
		"accessCtx", accessCtx,
		"cmd", cmd,
		"err", ret0,
		"duration", time.Since(start),
	)
	return ret0
}

type LoggingLoadLibraryHandler struct {
	inner  *LoadLibraryHandler
	logger logging.Logger
}

func NewLoggingLoadLibraryHandler(inner *LoadLibraryHandler, logger logging.Logger) *LoggingLoadLibraryHandler {
	return &LoggingLoadLibraryHandler{inner: inner, logger: logger}
}

func (h *LoggingLoadLibraryHandler) Execute(ctx context.Context) error {
	start := time.Now()
	ret0 := h.inner.Execute(ctx)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret0 != nil && !isNonLoggableError(ret0) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "LoadLibrary",
		"err", ret0,
		"duration", time.Since(start),
	)
	return ret0
}

type LoggingRemoteGetAlbumHandler struct {
	inner  *RemoteGetAlbumHandler
	logger logging.Logger
}

func NewLoggingRemoteGetAlbumHandler(inner *RemoteGetAlbumHandler, logger logging.Logger) *LoggingRemoteGetAlbumHandler {
	return &LoggingRemoteGetAlbumHandler{inner: inner, logger: logger}
}

func (h *LoggingRemoteGetAlbumHandler) Execute(ctx context.Context, accessCtx accessctx.AccessContext, cmd RemoteGetAlbum) (music.Album, error) {
	start := time.Now()
	ret0, ret1 := h.inner.Execute(ctx, accessCtx, cmd)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret1 != nil && !isNonLoggableError(ret1) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "RemoteGetAlbum",
		"accessCtx", accessCtx,
		"cmd", cmd,
		"ret0", ret0,
		"err", ret1,
		"duration", time.Since(start),
	)
	return ret0, ret1
}

type LoggingRemoteGetThumbnailHandler struct {
	inner  *RemoteGetThumbnailHandler
	logger logging.Logger
}

func NewLoggingRemoteGetThumbnailHandler(inner *RemoteGetThumbnailHandler, logger logging.Logger) *LoggingRemoteGetThumbnailHandler {
	return &LoggingRemoteGetThumbnailHandler{inner: inner, logger: logger}
}

func (h *LoggingRemoteGetThumbnailHandler) Execute(ctx context.Context, accessCtx accessctx.AccessContext, cmd RemoteGetThumbnail) (io.ReadCloser, error) {
	start := time.Now()
	ret0, ret1 := h.inner.Execute(ctx, accessCtx, cmd)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret1 != nil && !isNonLoggableError(ret1) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "RemoteGetThumbnail",
		"accessCtx", accessCtx,
		"cmd", cmd,
		"ret0", ret0,
		"err", ret1,
		"duration", time.Since(start),
	)
	return ret0, ret1
}

type LoggingRemoteGetTrackDurationHandler struct {
	inner  *RemoteGetTrackDurationHandler
	logger logging.Logger
}

func NewLoggingRemoteGetTrackDurationHandler(inner *RemoteGetTrackDurationHandler, logger logging.Logger) *LoggingRemoteGetTrackDurationHandler {
	return &LoggingRemoteGetTrackDurationHandler{inner: inner, logger: logger}
}

func (h *LoggingRemoteGetTrackDurationHandler) Execute(ctx context.Context, accessCtx accessctx.AccessContext, cmd RemoteGetTrackDuration) (music.TrackDuration, error) {
	start := time.Now()
	ret0, ret1 := h.inner.Execute(ctx, accessCtx, cmd)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret1 != nil && !isNonLoggableError(ret1) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "RemoteGetTrackDuration",
		"accessCtx", accessCtx,
		"cmd", cmd,
		"ret0", ret0,
		"err", ret1,
		"duration", time.Since(start),
	)
	return ret0, ret1
}

type LoggingRemoteKeepAliveStreamHandler struct {
	inner  *RemoteKeepAliveStreamHandler
	logger logging.Logger
}

func NewLoggingRemoteKeepAliveStreamHandler(inner *RemoteKeepAliveStreamHandler, logger logging.Logger) *LoggingRemoteKeepAliveStreamHandler {
	return &LoggingRemoteKeepAliveStreamHandler{inner: inner, logger: logger}
}

func (h *LoggingRemoteKeepAliveStreamHandler) Execute(ctx context.Context, accessCtx accessctx.AccessContext, cmd RemoteKeepAliveStream) error {
	start := time.Now()
	ret0 := h.inner.Execute(ctx, accessCtx, cmd)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret0 != nil && !isNonLoggableError(ret0) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "RemoteKeepAliveStream",
		"accessCtx", accessCtx,
		"cmd", cmd,
		"err", ret0,
		"duration", time.Since(start),
	)
	return ret0
}

type LoggingRemoteStartStreamingHandler struct {
	inner  *RemoteStartStreamingHandler
	logger logging.Logger
}

func NewLoggingRemoteStartStreamingHandler(inner *RemoteStartStreamingHandler, logger logging.Logger) *LoggingRemoteStartStreamingHandler {
	return &LoggingRemoteStartStreamingHandler{inner: inner, logger: logger}
}

func (h *LoggingRemoteStartStreamingHandler) Execute(ctx context.Context, accessCtx accessctx.AccessContext, cmd RemoteStartStreaming) (music.StreamId, error) {
	start := time.Now()
	ret0, ret1 := h.inner.Execute(ctx, accessCtx, cmd)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret1 != nil && !isNonLoggableError(ret1) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "RemoteStartStreaming",
		"accessCtx", accessCtx,
		"cmd", cmd,
		"ret0", ret0,
		"err", ret1,
		"duration", time.Since(start),
	)
	return ret0, ret1
}

type LoggingRemoteStreamFragmentHandler struct {
	inner  *RemoteStreamFragmentHandler
	logger logging.Logger
}

func NewLoggingRemoteStreamFragmentHandler(inner *RemoteStreamFragmentHandler, logger logging.Logger) *LoggingRemoteStreamFragmentHandler {
	return &LoggingRemoteStreamFragmentHandler{inner: inner, logger: logger}
}

func (h *LoggingRemoteStreamFragmentHandler) Execute(ctx context.Context, accessCtx accessctx.AccessContext, cmd RemoteStreamFragment) (io.ReadCloser, error) {
	start := time.Now()
	ret0, ret1 := h.inner.Execute(ctx, accessCtx, cmd)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret1 != nil && !isNonLoggableError(ret1) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "RemoteStreamFragment",
		"accessCtx", accessCtx,
		"cmd", cmd,
		"ret0", ret0,
		"err", ret1,
		"duration", time.Since(start),
	)
	return ret0, ret1
}

type LoggingRemoteStreamInitHandler struct {
	inner  *RemoteStreamInitHandler
	logger logging.Logger
}

func NewLoggingRemoteStreamInitHandler(inner *RemoteStreamInitHandler, logger logging.Logger) *LoggingRemoteStreamInitHandler {
	return &LoggingRemoteStreamInitHandler{inner: inner, logger: logger}
}

func (h *LoggingRemoteStreamInitHandler) Execute(ctx context.Context, accessCtx accessctx.AccessContext, cmd RemoteStreamInit) (io.ReadCloser, error) {
	start := time.Now()
	ret0, ret1 := h.inner.Execute(ctx, accessCtx, cmd)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret1 != nil && !isNonLoggableError(ret1) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "RemoteStreamInit",
		"accessCtx", accessCtx,
		"cmd", cmd,
		"ret0", ret0,
		"err", ret1,
		"duration", time.Since(start),
	)
	return ret0, ret1
}

type LoggingRemoteStreamPlaylistHandler struct {
	inner  *RemoteStreamPlaylistHandler
	logger logging.Logger
}

func NewLoggingRemoteStreamPlaylistHandler(inner *RemoteStreamPlaylistHandler, logger logging.Logger) *LoggingRemoteStreamPlaylistHandler {
	return &LoggingRemoteStreamPlaylistHandler{inner: inner, logger: logger}
}

func (h *LoggingRemoteStreamPlaylistHandler) Execute(ctx context.Context, accessCtx accessctx.AccessContext, cmd RemoteStreamPlaylist) (io.ReadCloser, error) {
	start := time.Now()
	ret0, ret1 := h.inner.Execute(ctx, accessCtx, cmd)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret1 != nil && !isNonLoggableError(ret1) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "RemoteStreamPlaylist",
		"accessCtx", accessCtx,
		"cmd", cmd,
		"ret0", ret0,
		"err", ret1,
		"duration", time.Since(start),
	)
	return ret0, ret1
}

type LoggingSearchHandler struct {
	inner  *SearchHandler
	logger logging.Logger
}

func NewLoggingSearchHandler(inner *SearchHandler, logger logging.Logger) *LoggingSearchHandler {
	return &LoggingSearchHandler{inner: inner, logger: logger}
}

func (h *LoggingSearchHandler) Execute(ctx context.Context, accessCtx accessctx.AccessContext, cmd Search) (library.SearchResults, error) {
	start := time.Now()
	ret0, ret1 := h.inner.Execute(ctx, accessCtx, cmd)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret1 != nil && !isNonLoggableError(ret1) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "Search",
		"accessCtx", accessCtx,
		"cmd", cmd,
		"ret0", ret0,
		"err", ret1,
		"duration", time.Since(start),
	)
	return ret0, ret1
}

type LoggingStartStreamingHandler struct {
	inner  *StartStreamingHandler
	logger logging.Logger
}

func NewLoggingStartStreamingHandler(inner *StartStreamingHandler, logger logging.Logger) *LoggingStartStreamingHandler {
	return &LoggingStartStreamingHandler{inner: inner, logger: logger}
}

func (h *LoggingStartStreamingHandler) Execute(ctx context.Context, accessCtx library.AccessContext, cmd StartStreaming) (music.StreamId, error) {
	start := time.Now()
	ret0, ret1 := h.inner.Execute(ctx, accessCtx, cmd)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret1 != nil && !isNonLoggableError(ret1) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "StartStreaming",
		"accessCtx", accessCtx,
		"cmd", cmd,
		"ret0", ret0,
		"err", ret1,
		"duration", time.Since(start),
	)
	return ret0, ret1
}

type LoggingStreamFragmentHandler struct {
	inner  *StreamFragmentHandler
	logger logging.Logger
}

func NewLoggingStreamFragmentHandler(inner *StreamFragmentHandler, logger logging.Logger) *LoggingStreamFragmentHandler {
	return &LoggingStreamFragmentHandler{inner: inner, logger: logger}
}

func (h *LoggingStreamFragmentHandler) Execute(accessCtx library.AccessContext, cmd StreamFragment) (ConvertedFile, error) {
	start := time.Now()
	ret0, ret1 := h.inner.Execute(accessCtx, cmd)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret1 != nil && !isNonLoggableError(ret1) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "StreamFragment",
		"accessCtx", accessCtx,
		"cmd", cmd,
		"ret0", ret0,
		"err", ret1,
		"duration", time.Since(start),
	)
	return ret0, ret1
}

type LoggingStreamInitHandler struct {
	inner  *StreamInitHandler
	logger logging.Logger
}

func NewLoggingStreamInitHandler(inner *StreamInitHandler, logger logging.Logger) *LoggingStreamInitHandler {
	return &LoggingStreamInitHandler{inner: inner, logger: logger}
}

func (h *LoggingStreamInitHandler) Execute(accessCtx library.AccessContext, cmd StreamInit) (ConvertedFile, error) {
	start := time.Now()
	ret0, ret1 := h.inner.Execute(accessCtx, cmd)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret1 != nil && !isNonLoggableError(ret1) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "StreamInit",
		"accessCtx", accessCtx,
		"cmd", cmd,
		"ret0", ret0,
		"err", ret1,
		"duration", time.Since(start),
	)
	return ret0, ret1
}

type LoggingStreamPlaylistHandler struct {
	inner  *StreamPlaylistHandler
	logger logging.Logger
}

func NewLoggingStreamPlaylistHandler(inner *StreamPlaylistHandler, logger logging.Logger) *LoggingStreamPlaylistHandler {
	return &LoggingStreamPlaylistHandler{inner: inner, logger: logger}
}

func (h *LoggingStreamPlaylistHandler) Execute(accessCtx library.AccessContext, cmd StreamPlaylist) (Playlist, error) {
	start := time.Now()
	ret0, ret1 := h.inner.Execute(accessCtx, cmd)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret1 != nil && !isNonLoggableError(ret1) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "StreamPlaylist",
		"accessCtx", accessCtx,
		"cmd", cmd,
		"ret0", ret0,
		"err", ret1,
		"duration", time.Since(start),
	)
	return ret0, ret1
}

type LoggingThumbnailHandler struct {
	inner  *ThumbnailHandler
	logger logging.Logger
}

func NewLoggingThumbnailHandler(inner *ThumbnailHandler, logger logging.Logger) *LoggingThumbnailHandler {
	return &LoggingThumbnailHandler{inner: inner, logger: logger}
}

func (h *LoggingThumbnailHandler) Execute(ctx context.Context, accessCtx library.AccessContext, id music.ThumbnailId) (ConvertedFile, error) {
	start := time.Now()
	ret0, ret1 := h.inner.Execute(ctx, accessCtx, id)
	logFn := h.logger.Debug
	msg := "handler executed"
	if ret1 != nil && !isNonLoggableError(ret1) {
		logFn = h.logger.Error
		msg = "handler failed"
	}
	logFn(msg,
		"handler", "Thumbnail",
		"accessCtx", accessCtx,
		"id", id,
		"ret0", ret0,
		"err", ret1,
		"duration", time.Since(start),
	)
	return ret0, ret1
}
