// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/boreq/eggplant/cmd/eggplant/commands/config"
	"github.com/boreq/eggplant/cmd/eggplant/commands/service"
	"github.com/boreq/eggplant/pkg/service/adapters/auth"
	"github.com/boreq/eggplant/pkg/service/application"
	auth2 "github.com/boreq/eggplant/pkg/service/application/auth"
	"github.com/boreq/eggplant/pkg/service/application/queries"
	"github.com/boreq/eggplant/pkg/service/ports/http"
)

// Injectors from wire.go:

func BuildService(conf *config.Config) (*service.Service, error) {
	db, err := newBolt(conf)
	if err != nil {
		return nil, err
	}
	bcryptPasswordHasher := auth.NewBcryptPasswordHasher()
	cryptoAccessTokenGenerator := auth.NewCryptoAccessTokenGenerator()
	userRepository, err := auth.NewUserRepository(db, bcryptPasswordHasher, cryptoAccessTokenGenerator)
	if err != nil {
		return nil, err
	}
	registerInitialHandler := auth2.NewRegisterInitialHandler(userRepository)
	registerHandler := auth2.NewRegisterHandler(userRepository)
	loginHandler := auth2.NewLoginHandler(userRepository)
	logoutHandler := auth2.NewLogoutHandler(userRepository)
	checkAccessTokenHandler := auth2.NewCheckAccessTokenHandler(userRepository)
	listHandler := auth2.NewListHandler(userRepository)
	createInvitationHandler := auth2.NewCreateInvitationHandler(userRepository)
	applicationAuth := application.Auth{
		RegisterInitial:  registerInitialHandler,
		Register:         registerHandler,
		Login:            loginHandler,
		Logout:           logoutHandler,
		CheckAccessToken: checkAccessTokenHandler,
		List:             listHandler,
		CreateInvitation: createInvitationHandler,
	}
	commands := application.Commands{}
	statsHandler := queries.NewStatsHandler(userRepository)
	applicationQueries := application.Queries{
		Stats: statsHandler,
	}
	applicationApplication := &application.Application{
		Auth:     applicationAuth,
		Commands: commands,
		Queries:  applicationQueries,
	}
	trackStore, err := newTrackStore(conf)
	if err != nil {
		return nil, err
	}
	store, err := newThumbnailStore(conf)
	if err != nil {
		return nil, err
	}
	library, err := newLibrary(trackStore, store, conf)
	if err != nil {
		return nil, err
	}
	handler, err := http.NewHandler(applicationApplication, library, trackStore, store)
	if err != nil {
		return nil, err
	}
	server := http.NewServer(handler)
	serviceService := service.NewService(server)
	return serviceService, nil
}
