name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v6

      - name: Run tests
        run: make ci
